[package]
name = "smolnet_core"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
publish = false

[features]
fuzzing = []

[dependencies]
rustler = "=0.38.0"
smoltcp = { version = "=0.14.0", default-features = false, features = [
  "std",
  "medium-ip",
  "proto-ipv4",
  "proto-ipv6",
  "auto-icmp-echo-reply",
  "async",
  "iface-max-addr-count-8",
  "socket-tcp",
  "socket-udp",
] }
